### ISSUE TITLE
CPR

### ISSUE THREAD

**Issue by Thymo-** [X39/XMS2#17]
Would be nice to have CPR next to only having defibs. As in real life you would need to perform CPR first to kinda 'kickstart' the heart in order for a defib to be effective.

**Comment by X39** [comment]
so the thing that needs to be archieved by this ticket is basically:
add a CPR feature in general (keeps away from death by flatline)
and add another flag to the defibrilator (maybe with chance? please confirm) that defibrillating a person requires a CPR before to be 100% successfull?

correct me if i got something wrong
