### ISSUE TITLE
Close the repository

### ISSUE THREAD

**Issue by X39** [X39/XMS2#43]
not rly ...

but as ACE3 now appeared with a THAT large team + support i see no chance that anybody would ever use this modification

its over guys

**Comment by michail-nikolaev** [comment]
:(

**Comment by X39** [comment]
quick side note:
after a few talks and multiple times i needed to explain why i see no way i could get anybody to use this mod i came to a conclusion:
IF i ever find anybody who is willed to REALLY work with me on the project permanent i will continue this modification
might not under the same name
but it will be continued if it ever happens
