### ISSUE TITLE
Integration into ACE Interaction 

### ISSUE THREAD

**Issue by Astrell** [X39/XMS2#45]
Integrate XMS2 into ACE Interaction with your "easy-going-features" like "Bandage complete Body" 
to decrease the needed buttons and lower menus. 

Advice: Dont do 3D Menu on the limps. Too many hate to follow the Limps of the patient in times of animation or whatever. Its just annoying. 

Why the Integration? 
XMS1 integration in AGM was the best, building a bridge between mods is always the best and the easiest for the users to understand. Make and use your own self and other interaction menue just confuse the user. Try to use one Standard. Alternative you can make the ACE 3D Menue back to 2D Menue like AGM, right now ACE doesnt have this feature.

**Comment by X39** [comment]
multiple questions to clear before this can start:
* is it possible to add menu actions "on the fly" without config?
* should only quickactions be used or should it be extended to "bandage each limb on its own" etc. ?

**Comment by Astrell** [comment]
after some thinking should it be done in two steps: 

Step 1: Reproduce ACE Medic Interaction even though its clumsy. 
Why? Let the Player FEEL the different, not seeing the difference. 
Don´t overstrain him that he have to learn a complete new interface and use. 
Through demonstration of flexibility in configuration we convince the player to use XMS2!

I am thinking it is necessary trough Step 1 to make it easier for the user to switch from ACE Medical to XMS2 without much difference in use. Nevertheless the quickactions should be integrated as comfort function. 

Step 2: Create a bridge between this simple menue and possibilities of the new XMS2 window to use the more advanced features. 

How its to be done? I dunno. Somewhat it feels too complicated from switching from the one menue to a complete other menue in purpose of use of the advanced features. Maybe is possible to make more displays and options in ACE Interaction without squeezing them into the 3D Limps of the Player?

**Comment by X39** [comment]
why bothering about how to do it when we can just do it directly 100%?

the current state of ACE medical ist pretty much also 100% what is covered by max. XMS2
the quickAcitons are just a new submenu then

**Comment by Astrell** [comment]
every limp is subdivided in two individual hitboxes. Upper and Lower Arm, etc. 
The + should be increasing because of that? How to display heart rate, blood pressure as continuous measurement? How to display (obviously) arterial damages or broken bones?

**Comment by X39** [comment]
well
the "fancy" ACE3 menu will do it
by using the good old "hint" box <3

**Comment by X39** [comment]
only problem by now is i have no fucking clue how the ACE3 interaction menu is actually "used"

**Comment by X39** [comment]
took quite some time to figure out how it works and how to fix a problem caused by its "design" ...
but yeah ...
here is how to use the ACE3 interaction menu:
```
test = ["test", "testAction", "\z\ace\addons\captives\UI\handcuff_ca.paa", {hint "statement";}, {true}, {}] call ACE_interact_menu_fnc_createAction; 
test2 = ["test2", "testAction2", "\z\ace\addons\captives\UI\handcuff_ca.paa", {hint "statement";}, {true}, {}] call ACE_interact_menu_fnc_createAction; 
result = ["B_Soldier_F", 1, ["ACE_SelfActions"], test] call ACE_interact_menu_fnc_addActionToClass;  
result = ["B_Soldier_F", 1, ["ACE_SelfActions", "test"], test2] call ACE_interact_menu_fnc_addActionToClass;  
```

whilst this is the workaround for the missing baseclass lookup
```
	_aceActionVariables = [];
	_len = count toArray "ace_interact_menu_act_";
	{
		if("ace_interact_menu_act_" == (_x select [0, _len])) then
		{
			_aceVariables pushBack (_x select [_len]);
		};
		false
	} count allVariables MissionNamespace;
	_recursiveAddActionToClass {
		params ["_typename", "_addActionToClassArray"];
		{
			if(_x isKindOf _typename || {_x isEqualTo _typename}) then 
			{
				_addActionToClassArray set [0, _x];
				_addActionToClassArray call ACE_interact_menu_fnc_addActionToClass;  
			};
			false
		}count _aceActionVariables;
	};
```

**Comment by flaver12** [comment]
You can add that simpler by just using the CfgVehicles for the unit: 

 //SelfAction Test
  class ACE_SelfActions {
            class Test_Action {
            displayName = "Test";
            distance = 2.0;
            condition = "[_player] call test_foo_bar";
            statement = "[_player] call test_foo_bar";
            showDisabled = 1;
            priority = 2;
            hotkey = "B";
            icon = "\Path\to\my\awsome\icons"
         };
        };
  //Action Test
  class ACE_Actions {
            class Test_Action {
            displayName = "Test";
            distance = 2.0;
            condition = "[_player] call test_foo2_bar";
            statement = "[_player] call test_foo2_bar";
            showDisabled = 1;
            priority = 2;
            hotkey = "B";
            icon = "\Path\to\my\awsome\icons"
         };
        };


For the medical part you can check this config here: https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Medical_SelfActions.hpp

**Comment by X39** [comment]
That would have worked with xms1 where the actions always where static
in xms2 they are added dynamicly using sqf
thus the option is not useful

**Comment by flaver12** [comment]
Okay sry, i didnt know ^^

**Comment by X39** [comment]
nothing to sorry :smile: you wanted to help but as i already said
the actions to perform have a too dynamic nature so that it is not possible to do it using classnames

**Comment by X39** [comment]
ticket gets implemented in ACE3_Interaction

**Comment by X39** [comment]
more and more issues show up during the implementation ...
adapting is quite hard
will take more time then expected ....

**Comment by X39** [comment]
using the ACE menu for each hitzone is not practicable for the end user --> we need more quickActions ...

**Comment by X39** [comment]
more or less done by a677a4a375c62206501f0b52e994b3001b3fc2f8

ToDo:
* Implement a proper QuickAction execution function which takes stuff like animations in account
* Add QuickActions for all actions possible in XMS2 (all limb stuff requires that sadly)

**Comment by flaver12** [comment]
Do we support load in vehicle for ace3?

**Comment by X39** [comment]
Better question is do we support it in general
kinda sure we dont do yet (check userconfig interaction extension)

**Comment by flaver12** [comment]
Okay, I mean we should it do in a possible way.
Lot of conmunitys will use ace and I dont know if they want two interaction menus.
I mean its just a thought, that we dont forgett that point.

**Comment by X39** [comment]
well
right now there is no way to load people into a vehicle (or out of a vehicle)
thus there are even more tickets to be created ...
as soon as i find the time to create em i will do so (need to check what tickets have to be created etc.)

**Comment by X39** [comment]
This ticket continues in:
* #55
* #56
* #57, #58, #60, #61, #63, #64
* #59, #62
