### ISSUE TITLE
[ACE3_BRIDGE] Put the old XLib Key Controls into CBA Key Controls

### ISSUE THREAD

**Issue by Astrell** [X39/XMS2#69]
The Key setting menu of XLib is Buggy. If the Debug Console is present its overlapping with the Key Setup for XLib and XMS2. 

Advice: Switch it to the CBA Key Manager. 

https://gyazo.com/67e9ed12daaf19995b614667c2d3b98e

**Comment by X39** [comment]
CBA Key handling stuff is way off from what is currently implemented in XLib, XMS2 and all other modifications maintained by me

WontFix due to XLib related problem (raised a bug in XLib project)
